branch-defaults:
  default:
    environment: null
deploy:
  artifact: build/libs/serviceability-cal-rest-1.0.0.jar
global:
  application_name: serviceability-cal
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
